all:
	gcc src/main.c src/menu.c src/message.c src/phrases.c src/word.c src/frequency.c src/crypto.c src/key.c src/ocurrence.c -o dist/main
run:
	dist/main
clean:
	rm dist/main
clean_exec:
	rm dist/main.exe